// Generated by cbindgen. Do not edit by hand; run:
//   cbindgen --config cbindgen.toml --output include/astropng_core.h

#ifndef ASTROPNG_CORE_H
#define ASTROPNG_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define TARGET_WIDTH 3840

#define TARGET_HEIGHT 2160

typedef enum AstropngFileStatus {
    AstropngFileStatus_Ok = 0,
    AstropngFileStatus_Skipped = 1,
    AstropngFileStatus_Failed = 2,
} AstropngFileStatus;

/**
 * Opaque cancellation handle. Create one, pass it to [`astropng_run`], and
 * call [`astropng_cancel_token_cancel`] from another thread to stop the run
 * after the current file. Must be freed with
 * [`astropng_cancel_token_free`] once the run has returned.
 */
typedef struct AstropngCancelToken AstropngCancelToken;

typedef struct AstropngOptions {
    const char *input_dir;
    /**
     * Nullable.
     */
    const char *output_dir;
    bool recursive;
    bool overwrite;
    bool resize4k;
    bool png_only;
    /**
     * Nullable.
     */
    const char *font_path;
    bool lookup;
    /**
     * Nullable explicit file list override; when non-null, `files_len` must
     * be its length.
     */
    const char *const *files;
    uintptr_t files_len;
    /**
     * `0` picks the same default as the Rust API (`min(available_parallelism, 8)`).
     */
    uintptr_t concurrency;
} AstropngOptions;

typedef struct AstropngProgress {
    uintptr_t index;
    uintptr_t total;
    const char *rel_path;
    enum AstropngFileStatus status;
    /**
     * Failure detail; null unless `status == Failed`.
     */
    const char *status_message;
    /**
     * Null unless the object was identified online and its title differs
     * from the file name.
     */
    const char *label;
    /**
     * Null unless there's something the caller should surface to the user.
     */
    const char *note;
} AstropngProgress;

typedef void (*AstropngProgressCallback)(const struct AstropngProgress *progress, void *user_data);

typedef struct AstropngSummary {
    uintptr_t total;
    uint32_t converted;
    uint32_t skipped;
    uint32_t failed;
    bool cancelled;
    char **warnings;
    uintptr_t warnings_len;
} AstropngSummary;

/**
 * Returns the crate version as a static, null-terminated string. Do not free.
 */
const char *astropng_version(void);

struct AstropngCancelToken *astropng_cancel_token_new(void);

/**
 * # Safety
 * `token` must be a pointer returned by [`astropng_cancel_token_new`] and
 * not yet freed.
 */
void astropng_cancel_token_cancel(const struct AstropngCancelToken *token);

/**
 * # Safety
 * `token` must be a pointer returned by [`astropng_cancel_token_new`],
 * not currently in use by a running [`astropng_run`] call, and not freed
 * twice.
 */
void astropng_cancel_token_free(struct AstropngCancelToken *token);

/**
 * Run the whole batch synchronously (blocks the calling thread until done,
 * cancelled, or a fatal setup error occurs). `callback` is invoked once per
 * file, possibly from a different native thread than the caller for each
 * invocation, but never concurrently with itself; callers that are not
 * thread-safe by default (e.g. most GUI toolkits) must marshal back to
 * their own main thread inside `callback`. Pointers inside the
 * [`AstropngProgress`] passed to `callback` are only valid for the duration
 * of that call.
 *
 * Returns `0` on success (`*out_summary` is set; free it with
 * [`astropng_summary_free`]). Returns non-zero on a fatal setup error or an
 * internal panic (`*out_error` is set; free it with
 * [`astropng_string_free`]). Exactly one of `*out_summary` / `*out_error`
 * is set on return.
 *
 * # Safety
 * `opts` must point to a valid, fully-initialized [`AstropngOptions`] whose
 * C-string fields are valid null-terminated UTF-8 (or null where the field
 * is documented nullable). `cancel` may be null (equivalent to a token that
 * is never cancelled). `out_summary` and `out_error` must be valid,
 * writable pointers.
 */
int32_t astropng_run(const struct AstropngOptions *opts,
                     const struct AstropngCancelToken *cancel,
                     AstropngProgressCallback callback,
                     void *user_data,
                     struct AstropngSummary **out_summary,
                     char **out_error);

/**
 * # Safety
 * `summary` must be a pointer produced by [`astropng_run`] and not freed
 * twice.
 */
void astropng_summary_free(struct AstropngSummary *summary);

/**
 * # Safety
 * `s` must be a pointer produced by this crate (e.g. via `out_error`) and
 * not freed twice.
 */
void astropng_string_free(char *s);

#endif  /* ASTROPNG_CORE_H */
